FROM nvidia/cuda:12.2.2-runtime-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get install -y --no-install-recommends \
    python3.11 \
    python3-pip \
    python3.11-dev \
    python3.11-venv \
    python3.11-distutils \
    libgl1 \
    git

RUN git clone https://github.com/Haidra-Org/horde-worker-reGen.git && \
    cd /horde-worker-reGen && \
    python3.11 -m venv venv && \
    . venv/bin/activate && \
    python -m pip install --upgrade pip && \
    python -m pip install -r /horde-worker-reGen/requirements.txt -U --extra-index-url https://download.pytorch.org/whl/cu124 && \
    python -m pip install opencv-python-headless -U && \
    python -m pip cache purge

CMD cd /horde-worker-reGen && \
    git pull && \
    . venv/bin/activate && \
    python -m pip install -r requirements.txt opencv-python-headless -U && \
    python download_models.py -e && \
    python run_worker.py -e
